# Autogenerated wrapper script for libdatachannel_jll for aarch64-apple-darwin
export libdatachannel

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("libdatachannel")
JLLWrappers.@declare_library_product(libdatachannel, "@rpath/libdatachannel.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libdatachannel,
        "lib/libdatachannel.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
